name: Node.js

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.0
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20.x
      - name: Setup
        run: npm install
      - name: Compile
        run: npm run compile
      - name: Package
        run: npm run package
      - name: Start xvfb
        run: |
          # cf. https://github.com/microsoft/vscode-test/issues/47#issuecomment-546952277
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - name: Run tests
        env:
          CODE_VERSION: ""
          DISPLAY: ":99.0"
        run: npm test
