name: Node.js

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18.x

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup
        run: npm install
      - name: Compile
        run: npm run compile
      - name: Package
        run: npm run package
      - name: Start xvfb
        run: |
          # cf. https://github.com/microsoft/vscode-test/issues/47#issuecomment-546952277
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - name: Run tests
        env:
          CODE_VERSION: ""
          DISPLAY: ":99.0"
        run: npm test
