name: Node.js

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup ledgerlint
      run: |
        LEDGERLINT_VERSION=0.0.1
        FILENAME=ledgerlint_${LEDGERLINT_VERSION}_linux_amd64.tar.gz

        wget --no-verbose https://github.com/oshikiri/ledgerlint/releases/download/v${LEDGERLINT_VERSION}/${FILENAME}
        tar xzvf ${FILENAME}

        mkdir -p $HOME/.local/bin
        PATH=$PATH:$HOME/.local/bin
        mv ledgerlint $HOME/.local/bin
    - name: Setup
      run: npm install
    - name: Compile
      run: npm run compile
    - name: vsce
      run: |
          npm install -g vsce
          vsce package
    - name: Start xvfb (cf. https://github.com/microsoft/vscode-test/issues/47#issuecomment-546952277)
      run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - name: Run tests
      env:
          CODE_VERSION: ''
          DISPLAY: ':99.0'
      run: |
        cd server && npm test && cd -
        npm test
