name: Node.js

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup ledgerlint
      run: |
        echo $PATH
        LEDGERLINT_VERSION=0.0.1
        FILENAME=ledgerlint_${LEDGERLINT_VERSION}_darwin_amd64.tar.gz
        wget https://github.com/oshikiri/ledgerlint/releases/download/v${LEDGERLINT_VERSION}/${FILENAME}
        tar xzvf ${FILENAME}
        mkdir -p $HOME/.local/bin
        mv ledgerlint $HOME/.local/bin
    - name: Setup
      run: npm install
    - name: Compile
      run: npm run compile
    - name: vsce
      run: |
          npm install -g vsce
          vsce package
    - name: Run tests
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: npm test
