name: publish

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x

    - name: Build
      run: |
        npm install
        npm run package
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "generic-annotator-*.vsix"
        token: ${{ secrets.GITHUB_TOKEN }}
