name: publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0

      - name: Use Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20.x

      - name: Build
        run: |
          npm install
          npm run package
      - uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "generic-annotator-*.vsix"
          token: ${{ secrets.GITHUB_TOKEN }}
